[workspace]
members = [
    "apps/toolkit",
    "crates/ui/toolkit-ui",
    "crates/formats/pam-codec",
    "crates/formats/serde_rton",
    "crates/pam/core",
    "crates/pam/formats",
    "crates/pam/native-window",
    "crates/pam/renderer",
    "crates/pam/worker",
    "crates/rton/core",
    "crates/rton/worker",
    "crates/tools/pam-tool",
    "crates/tools/rton-tool",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
repository = "https://github.com/LambdaEd1th/ed1ths-pvz-toolkit"
publish = false

[workspace.dependencies]
base64 = "0.22"
bytemuck = { version = "1.24", features = ["derive"] }
crc32fast = "1.5"
dioxus = { version = "0.7.9", default-features = false }
dioxus-free-icons = { version = "0.10", features = ["lucide"] }
dioxus-html = "0.7.9"
futures-channel = "0.3"
futures-util = "0.3"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
image-webp = "0.2.4"
pam-codec = { path = "crates/formats/pam-codec", version = "0.1.2" }
parking_lot = "0.12"
png = "0.18"
quick-xml = "0.41"
rayon = "1"
regex = "1.13"
roxmltree = "0.21"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = { version = "1", features = ["float_roundtrip"] }
serde_rton = { path = "crates/formats/serde_rton", version = "0.4.0", default-features = false }
serde_yaml = "0.9.33"
thiserror = "2"
toml = "1.1"
toolkit-ui = { path = "crates/ui/toolkit-ui" }
wgpu = { version = "30", features = ["webgl"] }
zip = { version = "8", default-features = false, features = ["deflate"] }

[profile.release]
lto = "thin"
opt-level = "s"
strip = true
