[application]
name = "pvz-toolkit"
default_platform = "web"
out_dir = "dist"

[bundle]
identifier = "io.github.lambdaed1th.pvz-toolkit"
publisher = "Ed1th"
category = "DeveloperTool"
short_description = "PvZ resource archive, data, animation, audio, and compression tools"

[web.app]
title = "Ed1th's PvZ Toolkit"

[web.watcher]
reload_html = true

[desktop.app]
title = "Ed1th's PvZ Toolkit"
