[package]
name = "particle-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Internal Particle workspace for Ed1th's PvZ Toolkit"

[lib]
path = "src/lib.rs"

[dependencies]
dioxus-html.workspace = true
particle-codec.workspace = true
toolkit-ui.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { workspace = true, features = ["desktop"] }
rfd.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { workspace = true, features = ["web"] }
js-sys.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Blob",
    "Document",
    "HtmlAnchorElement",
    "Location",
    "Url",
    "Window",
] }
