[package]
name = "rsb-patch-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Internal RSBPatch workspace for Ed1th's PvZ Toolkit"

[lib]
path = "src/lib.rs"

[dependencies]
dioxus-html.workspace = true
rsb_patch_worker.workspace = true
toolkit-ui.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { workspace = true, features = ["desktop"] }
futures-channel.workspace = true
rayon.workspace = true
rfd.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { workspace = true, features = ["web"] }
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Blob",
    "Document",
    "HtmlAnchorElement",
    "Location",
    "MessageEvent",
    "Url",
    "Window",
    "Worker",
    "WorkerOptions",
    "WorkerType",
] }
