#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct LibraryDescriptor {
    pub(crate) name: &'static str,
    pub(crate) version: &'static str,
    pub(crate) repository: &'static str,
    pub(crate) family: &'static str,
    pub(crate) tags: &'static [&'static str],
}

pub(crate) const LIBRARIES: [LibraryDescriptor; 14] = [
    LibraryDescriptor {
        name: "rsb-archive",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/rsb-archive",
        family: "archive",
        tags: &["RSB", "RSG", "PTX"],
    },
    LibraryDescriptor {
        name: "rsb-patch",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/rsb-patch",
        family: "patch",
        tags: &["RSBP", "VCDIFF", "MD5"],
    },
    LibraryDescriptor {
        name: "pak-archive",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/pak-archive",
        family: "archive",
        tags: &["PAK", "XOR", "ZIP"],
    },
    LibraryDescriptor {
        name: "dzip-archive",
        version: "0.5.1",
        repository: "https://github.com/LambdaEd1th/dzip-archive",
        family: "archive",
        tags: &["DZip", "Volumes", "LZMA"],
    },
    LibraryDescriptor {
        name: "smf-container",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/smf-container",
        family: "container",
        tags: &["SMF", "zlib", "MD5"],
    },
    LibraryDescriptor {
        name: "serde-rton",
        version: "0.4.0",
        repository: "https://github.com/LambdaEd1th/serde-rton",
        family: "data",
        tags: &["Serde", "RTON", "Crypto"],
    },
    LibraryDescriptor {
        name: "pam-codec",
        version: "0.1.2",
        repository: "https://github.com/LambdaEd1th/pam-codec",
        family: "animation",
        tags: &["PAM", "Animation", "Serde"],
    },
    LibraryDescriptor {
        name: "particle-codec",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/particle-codec",
        family: "animation",
        tags: &["Particle", "Trail", "XML"],
    },
    LibraryDescriptor {
        name: "reanim-codec",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/reanim-codec",
        family: "animation",
        tags: &["REANIM", "XFL", "Compiled"],
    },
    LibraryDescriptor {
        name: "wem-audio",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/wem-audio",
        family: "audio",
        tags: &["WEM", "Vorbis", "WAV"],
    },
    LibraryDescriptor {
        name: "bnk-archive",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/bnk-archive",
        family: "audio",
        tags: &["BNK", "HIRC", "WEM"],
    },
    LibraryDescriptor {
        name: "compiled-text",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/compiled-text",
        family: "security",
        tags: &["Rijndael", "Base64", "Text"],
    },
    LibraryDescriptor {
        name: "crypt-data",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/crypt-data",
        family: "security",
        tags: &["CRYPT_RES", "XOR", "Local"],
    },
    LibraryDescriptor {
        name: "newton-manifest",
        version: "0.1.0",
        repository: "https://github.com/LambdaEd1th/newton-manifest",
        family: "data",
        tags: &["NEWTON", "Manifest", "Atlas"],
    },
];
