[package]
name = "rton-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
authors = ["LambdaEd1th"]
description = "Internal RTON workspace for Ed1th's PvZ Toolkit"

[lib]
path = "src/lib.rs"

[dependencies]
dioxus-free-icons.workspace = true
dioxus-html.workspace = true
fluent-bundle.workspace = true
log.workspace = true
ropey.workspace = true
rton_editor_core.workspace = true
serde.workspace = true
serde_json.workspace = true
toolkit-ui.workspace = true
unic-langid.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { workspace = true, features = ["desktop"] }
futures-timer.workspace = true
memmap2.workspace = true
rayon.workspace = true
rfd.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { workspace = true, features = ["web"] }
js-sys.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Blob",
    "ClipboardEvent",
    "console",
    "DataTransfer",
    "DataTransferItem",
    "DataTransferItemList",
    "Document",
    "DragEvent",
    "Element",
    "ErrorEvent",
    "File",
    "FileSystemDirectoryEntry",
    "FileSystemDirectoryReader",
    "FileSystemEntry",
    "FileSystemFileEntry",
    "HtmlAnchorElement",
    "MessageEvent",
    "Navigator",
    "Response",
    "Storage",
    "Url",
    "Window",
    "Worker",
    "WorkerOptions",
    "WorkerType",
] }
